<?php
/**
 * Address Validator select
 *
 * @category   Aydus
 * @package    Aydus_Addressvalidator
 * @author     Aydus <davidt@aydus.com>
 */

$storeId = Mage::app()->getStore()->getId();
$tooManyAttemptsUrl = Mage::getStoreConfig('aydus_addressvalidator/configuration/too_many_attempts_url',$storeId);
$customerServiceUrl = $this->getUrl($tooManyAttemptsUrl);
?>


<div id="av-popup" style="display: none">
    <div id="av-popup-overlay"></div>
    <div id="av-popup-content">
        <form>
            <input type="hidden" id="address-form" name="address_form" value="" />
            <h4></h4>

            <ul class='radios'>
            </ul>

            <div class="button-set buttons actions">
                <button class="button back">
                    <span><span><?php echo $this->__('Back') ?></span></span>
                </button>

                <button class="button select disabled">
                    <span><span><?php echo $this->__('Select') ?></span></span>
                </button>

                <button class="button skip">
                    <span><span><?php echo $this->__('Skip') ?></span></span>
                </button>

                <button class="button okay" href="<?php echo $customerServiceUrl ?>">
                    <span><span><?php echo $this->__('Customer Service') ?></span></span>
                </button>

            </div>				
        </form>        
    </div>
</div>



<script src="<?php echo $this->getSkinUrl('js/aydus/addressvalidator/address.js') ?>"></script>
<script>
    addressValidator.init({
        auto_populate: <?php echo (Mage::getStoreConfig('aydus_addressvalidator/configuration/auto_populate')) ? 'true' : 'false' ?>,
        allow_bypass: <?php echo (Mage::getStoreConfig('aydus_addressvalidator/configuration/allow_bypass')) ? 'true' : 'false' ?>
    });
</script>
